# Site settings
title:       Oddball
email:
author:      Yan Foto
description: "A Material Design light light theme for Jekyll"
baseurl:     ""
url:         "http://quaintous.github.io/oddball"
language: en

# Google analytics
google_analytics:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:year/:month/:day/:title/
paginate:     3
sass:
  compressed: true
gems: [jekyll-paginate]
